--
-- PostgreSQL database dump
--

\restrict HYkv22ylMFeCSkHxy2J2IBqBcEptIOQGwaKW8gL3TqAWmzVb8dIhRtPOiB8aKyC

-- Dumped from database version 17.7
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-20 10:18:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16386)
-- Name: cart_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    discount_price numeric(10,2),
    original_price numeric(10,2) NOT NULL,
    product_id bigint NOT NULL,
    product_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL
);


ALTER TABLE public.cart_items OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16385)
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16392)
-- Name: carts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.carts OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16391)
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3429 (class 0 OID 16386)
-- Dependencies: 218
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_items (id, created_at, updated_at, discount_price, original_price, product_id, product_name, quantity, cart_id) FROM stdin;
36	2025-12-19 00:33:26.396986+00	2025-12-19 00:33:26.396986+00	990000.00	1200000.00	52	Balo North Face Fuse Box	1	1
31	2025-12-18 13:46:15.335637+00	2025-12-19 00:33:26.432684+00	11990000.00	13990000.00	21	iPad Air 5 M1 64GB WiFi	1	1
\.


--
-- TOC entry 3431 (class 0 OID 16392)
-- Dependencies: 220
-- Data for Name: carts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carts (id, created_at, updated_at, user_id) FROM stdin;
1	2025-12-16 04:21:53.019948+00	2025-12-19 00:33:26.432144+00	3
2	2025-12-18 06:02:49.895767+00	2025-12-20 02:31:47.473198+00	1
\.


--
-- TOC entry 3437 (class 0 OID 0)
-- Dependencies: 217
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 39, true);


--
-- TOC entry 3438 (class 0 OID 0)
-- Dependencies: 219
-- Name: carts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carts_id_seq', 2, true);


--
-- TOC entry 3277 (class 2606 OID 16390)
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3279 (class 2606 OID 16396)
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- TOC entry 3281 (class 2606 OID 16398)
-- Name: carts uk64t7ox312pqal3p7fg9o503c2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);


--
-- TOC entry 3282 (class 2606 OID 16399)
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


-- Completed on 2025-12-20 10:18:24

--
-- PostgreSQL database dump complete
--

\unrestrict HYkv22ylMFeCSkHxy2J2IBqBcEptIOQGwaKW8gL3TqAWmzVb8dIhRtPOiB8aKyC

