--
-- PostgreSQL database dump
--

\restrict cqqNt0WmHQ4lFapG2EdIe3sLmaUBxgcDqu3eJZb5YOnCWKOV7JUwLGkzfPrwszS

-- Dumped from database version 17.7
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-20 10:21:09

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16389)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean NOT NULL,
    message character varying(255),
    reference_id character varying(255),
    title character varying(255),
    type character varying(255),
    user_id bigint,
    target_role character varying(255)
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16388)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3419 (class 0 OID 16389)
-- Dependencies: 218
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, created_at, is_read, message, reference_id, title, type, user_id, target_role) FROM stdin;
1	2025-12-17 21:50:13.40848	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
114	2025-12-18 12:08:27.949933	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
136	2025-12-18 12:09:03.477707	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
137	2025-12-18 12:10:55.333021	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
139	2025-12-18 12:14:16.577869	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
143	2025-12-18 12:15:40.631899	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
147	2025-12-18 12:15:40.693854	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
193	2025-12-18 12:29:28.67831	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
198	2025-12-18 12:29:28.764957	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
219	2025-12-18 12:30:40.129852	f	Đơn hàng #6 đã được tạo thành công! Tổng tiền: 450000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	6	Đơn hàng mới	ORDER	3	\N
222	2025-12-18 12:34:16.083572	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
227	2025-12-18 12:34:16.179147	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
229	2025-12-18 12:34:16.188447	f	Đơn hàng #6 đã được tạo thành công! Tổng tiền: 450000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	6	Đơn hàng mới	ORDER	3	\N
249	2025-12-18 12:35:34.413593	f	Đơn hàng #6 đã được hủy thành công. Số tiền 450000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	6	Đơn hàng đã hủy	ORDER	3	\N
254	2025-12-18 12:39:31.057798	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
256	2025-12-18 12:39:31.174768	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
285	2025-12-18 12:45:12.503742	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
291	2025-12-18 12:45:12.624734	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
293	2025-12-18 12:45:12.634963	f	Đơn hàng #5 đã được hủy thành công. Số tiền 3800000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	5	Đơn hàng đã hủy	ORDER	3	\N
295	2025-12-18 12:45:12.645487	f	Đơn hàng #7 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	7	Đơn hàng mới	ORDER	3	\N
315	2025-12-18 12:45:12.862512	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
317	2025-12-18 13:01:43.942879	f	Thanh toán thành công! Đơn hàng #7 đã được thanh toán 3800000.00 VND. Đơn hàng của bạn đang được xử lý.	7	Thanh toán thành công	PAYMENT	3	\N
319	2025-12-18 13:01:43.978234	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
321	2025-12-18 13:01:43.981419	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
324	2025-12-18 13:01:44.002835	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
325	2025-12-18 13:01:44.002835	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
327	2025-12-18 13:01:44.008218	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
329	2025-12-18 13:01:44.013489	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
332	2025-12-18 13:01:44.019251	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
333	2025-12-18 13:01:44.024742	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
334	2025-12-18 13:01:44.029975	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
335	2025-12-18 13:01:44.03594	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
336	2025-12-18 13:01:44.041164	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
337	2025-12-18 13:01:44.046403	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
338	2025-12-18 13:01:44.051707	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
339	2025-12-18 13:01:44.056469	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
340	2025-12-18 13:01:44.059628	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
341	2025-12-18 13:01:44.06607	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
342	2025-12-18 13:01:44.070759	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
343	2025-12-18 13:01:44.075448	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
344	2025-12-18 13:01:44.079623	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
6	2025-12-17 21:50:13.504774	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
4	2025-12-17 21:50:13.496346	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
2	2025-12-17 21:50:13.40848	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
115	2025-12-18 12:08:27.949933	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
117	2025-12-18 12:08:28.005935	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
166	2025-12-18 12:22:59.073969	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
170	2025-12-18 12:22:59.140412	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
194	2025-12-18 12:29:28.67831	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
196	2025-12-18 12:29:28.765465	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
223	2025-12-18 12:34:16.083572	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
226	2025-12-18 12:34:16.179147	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
228	2025-12-18 12:34:16.188447	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
230	2025-12-18 12:34:16.196591	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
231	2025-12-18 12:34:16.205153	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
232	2025-12-18 12:34:16.214151	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
233	2025-12-18 12:34:16.223327	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
234	2025-12-18 12:34:16.232704	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
235	2025-12-18 12:34:16.242461	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
236	2025-12-18 12:34:16.251854	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
237	2025-12-18 12:34:16.260541	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
238	2025-12-18 12:34:16.269337	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
239	2025-12-18 12:34:16.277817	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
240	2025-12-18 12:34:16.286481	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
241	2025-12-18 12:34:16.295672	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
242	2025-12-18 12:34:16.304329	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
243	2025-12-18 12:34:16.314124	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
244	2025-12-18 12:34:16.323591	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
245	2025-12-18 12:34:16.333407	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
246	2025-12-18 12:34:16.341991	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
247	2025-12-18 12:34:16.351713	f	Bạn đã thêm 1 x Ví Nam Da Bò Khắc Tên vào giỏ hàng. Giá: 450000.00	54	Thêm vào giỏ hàng	CART	3	\N
250	2025-12-18 12:35:40.456506	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
255	2025-12-18 12:39:31.057798	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
257	2025-12-18 12:39:31.174768	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
262	2025-12-18 12:39:31.187932	f	Đơn hàng #5 đã được hủy thành công. Số tiền 3800000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	5	Đơn hàng đã hủy	ORDER	3	\N
264	2025-12-18 12:39:31.210256	f	Đơn hàng #7 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	7	Đơn hàng mới	ORDER	3	\N
286	2025-12-18 12:45:12.503742	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
289	2025-12-18 12:45:12.623402	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
292	2025-12-18 12:45:12.633963	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
296	2025-12-18 12:45:12.643968	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
298	2025-12-18 12:45:12.657712	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
299	2025-12-18 12:45:12.668518	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
300	2025-12-18 12:45:12.688248	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
301	2025-12-18 12:45:12.702703	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
302	2025-12-18 12:45:12.713779	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
116	2025-12-18 12:08:27.949933	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
118	2025-12-18 12:08:28.005935	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
119	2025-12-18 12:08:28.011231	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
120	2025-12-18 12:08:28.016451	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
121	2025-12-18 12:08:28.022193	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
122	2025-12-18 12:08:28.032667	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
123	2025-12-18 12:08:28.041426	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
124	2025-12-18 12:08:28.049685	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
125	2025-12-18 12:08:28.056818	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
126	2025-12-18 12:08:28.063138	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
127	2025-12-18 12:08:28.069633	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
128	2025-12-18 12:08:28.074871	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
129	2025-12-18 12:08:28.080137	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
130	2025-12-18 12:08:28.085918	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
131	2025-12-18 12:08:28.091189	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
132	2025-12-18 12:08:28.096211	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
133	2025-12-18 12:08:28.101645	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
134	2025-12-18 12:08:28.10633	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
135	2025-12-18 12:08:28.11077	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
138	2025-12-18 12:14:12.365231	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
168	2025-12-18 12:22:59.073969	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
171	2025-12-18 12:22:59.140412	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
195	2025-12-18 12:29:28.67831	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
199	2025-12-18 12:29:28.765465	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
221	2025-12-18 12:34:16.083572	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
225	2025-12-18 12:34:16.179147	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
265	2025-12-18 12:39:31.213963	f	Đơn hàng #6 đã được hủy thành công. Số tiền 450000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	6	Đơn hàng đã hủy	ORDER	3	\N
287	2025-12-18 12:45:12.503742	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
290	2025-12-18 12:45:12.623402	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
294	2025-12-18 12:45:12.637218	f	Đơn hàng #6 đã được tạo thành công! Tổng tiền: 450000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	6	Đơn hàng mới	ORDER	3	\N
297	2025-12-18 12:45:12.64709	f	Đơn hàng #6 đã được hủy thành công. Số tiền 450000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	6	Đơn hàng đã hủy	ORDER	3	\N
316	2025-12-18 12:48:33.130362	f	Thanh toán thành công! Đơn hàng #7 đã được thanh toán 3800000.00 VND. Đơn hàng của bạn đang được xử lý.	7	Thanh toán thành công	PAYMENT	3	\N
318	2025-12-18 13:01:43.978234	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
320	2025-12-18 13:01:43.978234	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
322	2025-12-18 13:01:44.002835	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
323	2025-12-18 13:01:44.002835	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
326	2025-12-18 13:01:44.008218	f	Đơn hàng #5 đã được hủy thành công. Số tiền 3800000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	5	Đơn hàng đã hủy	ORDER	3	\N
328	2025-12-18 13:01:44.008746	f	Đơn hàng #6 đã được tạo thành công! Tổng tiền: 450000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	6	Đơn hàng mới	ORDER	3	\N
330	2025-12-18 13:01:44.01401	f	Đơn hàng #6 đã được hủy thành công. Số tiền 450000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	6	Đơn hàng đã hủy	ORDER	3	\N
331	2025-12-18 13:01:44.01401	f	Đơn hàng #7 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	7	Đơn hàng mới	ORDER	3	\N
345	2025-12-18 13:01:44.084405	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
346	2025-12-18 13:01:44.088626	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
48	2025-12-18 00:59:34.53734	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
46	2025-12-18 00:59:34.526685	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
140	2025-12-18 12:15:40.631899	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
144	2025-12-18 12:15:40.693854	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
148	2025-12-18 12:15:40.700268	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
149	2025-12-18 12:15:40.705618	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
150	2025-12-18 12:15:40.711519	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
151	2025-12-18 12:15:40.717883	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
152	2025-12-18 12:15:40.724704	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
153	2025-12-18 12:15:40.730389	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
154	2025-12-18 12:15:40.736132	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
155	2025-12-18 12:15:40.74093	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
156	2025-12-18 12:15:40.746408	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
157	2025-12-18 12:15:40.751721	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
158	2025-12-18 12:15:40.756439	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
159	2025-12-18 12:15:40.761681	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
160	2025-12-18 12:15:40.766473	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
161	2025-12-18 12:15:40.771714	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
162	2025-12-18 12:15:40.777476	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
163	2025-12-18 12:15:40.782766	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
164	2025-12-18 12:15:40.788284	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
165	2025-12-18 12:15:40.793511	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
167	2025-12-18 12:22:59.073969	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
172	2025-12-18 12:22:59.140412	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
174	2025-12-18 12:22:59.14805	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
175	2025-12-18 12:22:59.155073	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
176	2025-12-18 12:22:59.161565	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
177	2025-12-18 12:22:59.169693	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
178	2025-12-18 12:22:59.177341	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
179	2025-12-18 12:22:59.185402	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
180	2025-12-18 12:22:59.192465	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
181	2025-12-18 12:22:59.198866	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
182	2025-12-18 12:22:59.205145	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
183	2025-12-18 12:22:59.211144	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
184	2025-12-18 12:22:59.217425	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
185	2025-12-18 12:22:59.223242	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
186	2025-12-18 12:22:59.229125	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
187	2025-12-18 12:22:59.234479	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
188	2025-12-18 12:22:59.240328	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
189	2025-12-18 12:22:59.245113	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
190	2025-12-18 12:22:59.25164	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
191	2025-12-18 12:22:59.257726	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
218	2025-12-18 12:30:36.522841	f	Bạn đã thêm 1 x Ví Nam Da Bò Khắc Tên vào giỏ hàng. Giá: 450000.00	54	Thêm vào giỏ hàng	CART	3	\N
252	2025-12-18 12:39:31.057798	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
259	2025-12-18 12:39:31.179834	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
261	2025-12-18 12:39:31.197665	f	Đơn hàng #6 đã được tạo thành công! Tổng tiền: 450000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	6	Đơn hàng mới	ORDER	3	\N
141	2025-12-18 12:15:40.631899	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
145	2025-12-18 12:15:40.693854	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
169	2025-12-18 12:22:59.073969	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
173	2025-12-18 12:22:59.140412	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
220	2025-12-18 12:34:16.083572	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
224	2025-12-18 12:34:16.179147	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
248	2025-12-18 12:35:21.554841	f	Đơn hàng #5 đã được hủy thành công. Số tiền 3800000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	5	Đơn hàng đã hủy	ORDER	3	\N
251	2025-12-18 12:35:42.901626	f	Đơn hàng #7 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	7	Đơn hàng mới	ORDER	3	\N
253	2025-12-18 12:39:31.057798	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
258	2025-12-18 12:39:31.174768	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
260	2025-12-18 12:39:31.187932	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
263	2025-12-18 12:39:31.207659	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
266	2025-12-18 12:39:31.222318	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
267	2025-12-18 12:39:31.230886	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
268	2025-12-18 12:39:31.241281	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
269	2025-12-18 12:39:31.250345	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
270	2025-12-18 12:39:31.259452	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
271	2025-12-18 12:39:31.268223	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
272	2025-12-18 12:39:31.277501	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
273	2025-12-18 12:39:31.286333	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
274	2025-12-18 12:39:31.293887	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
275	2025-12-18 12:39:31.302352	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
276	2025-12-18 12:39:31.309482	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
277	2025-12-18 12:39:31.316409	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
278	2025-12-18 12:39:31.329993	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
279	2025-12-18 12:39:31.339132	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
280	2025-12-18 12:39:31.347717	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
281	2025-12-18 12:39:31.35712	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
282	2025-12-18 12:39:31.365622	f	Bạn đã thêm 1 x Ví Nam Da Bò Khắc Tên vào giỏ hàng. Giá: 450000.00	54	Thêm vào giỏ hàng	CART	3	\N
283	2025-12-18 12:39:31.37332	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
284	2025-12-18 12:45:12.503742	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
288	2025-12-18 12:45:12.623402	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
303	2025-12-18 12:45:12.721829	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
304	2025-12-18 12:45:12.729911	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
305	2025-12-18 12:45:12.739728	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
306	2025-12-18 12:45:12.748305	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
307	2025-12-18 12:45:12.760158	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
308	2025-12-18 12:45:12.769176	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
309	2025-12-18 12:45:12.780378	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
310	2025-12-18 12:45:12.788944	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
311	2025-12-18 12:45:12.799452	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
312	2025-12-18 12:45:12.810832	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
313	2025-12-18 12:45:12.823788	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
314	2025-12-18 12:45:12.843878	f	Bạn đã thêm 1 x Ví Nam Da Bò Khắc Tên vào giỏ hàng. Giá: 450000.00	54	Thêm vào giỏ hàng	CART	3	\N
113	2025-12-18 11:55:37.586182	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
112	2025-12-18 11:53:16.825071	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
111	2025-12-18 11:51:18.167657	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
110	2025-12-18 11:51:06.693887	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
109	2025-12-18 11:47:20.286116	t	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
108	2025-12-18 11:47:20.278463	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
107	2025-12-18 11:47:20.264906	t	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
106	2025-12-18 11:47:20.256318	t	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
105	2025-12-18 11:47:20.2483	t	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
104	2025-12-18 11:47:20.240148	t	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
103	2025-12-18 11:47:20.232547	t	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
102	2025-12-18 11:47:20.224818	t	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
101	2025-12-18 11:47:20.217247	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
100	2025-12-18 11:47:20.210185	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
99	2025-12-18 11:47:20.203168	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
98	2025-12-18 11:47:20.196019	t	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
97	2025-12-18 11:47:20.189559	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
96	2025-12-18 11:47:20.181881	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
95	2025-12-18 11:47:20.181881	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
92	2025-12-18 11:47:20.100303	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
94	2025-12-18 11:47:20.100303	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
93	2025-12-18 11:47:20.100303	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
91	2025-12-18 11:39:28.018496	t	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
142	2025-12-18 12:15:40.631899	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
146	2025-12-18 12:15:40.693854	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
192	2025-12-18 12:29:28.67831	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
197	2025-12-18 12:29:28.764957	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
200	2025-12-18 12:29:28.772501	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
201	2025-12-18 12:29:28.779531	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
202	2025-12-18 12:29:28.78628	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
203	2025-12-18 12:29:28.794406	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
204	2025-12-18 12:29:28.802492	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
205	2025-12-18 12:29:28.811044	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
206	2025-12-18 12:29:28.820247	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
207	2025-12-18 12:29:28.828678	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
208	2025-12-18 12:29:28.836641	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
209	2025-12-18 12:29:28.845485	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
210	2025-12-18 12:29:28.853552	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
211	2025-12-18 12:29:28.861704	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
212	2025-12-18 12:29:28.87051	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
213	2025-12-18 12:29:28.878039	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
214	2025-12-18 12:29:28.886135	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
215	2025-12-18 12:29:28.893166	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
216	2025-12-18 12:29:28.900182	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
217	2025-12-18 12:29:28.906071	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
90	2025-12-18 11:35:41.028493	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
89	2025-12-18 11:35:24.385363	t	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
88	2025-12-18 11:34:35.0855	t	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
87	2025-12-18 11:17:07.169065	t	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
86	2025-12-18 11:11:37.462184	t	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
85	2025-12-18 11:11:07.944332	t	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
84	2025-12-18 11:07:41.485458	t	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
83	2025-12-18 10:59:17.560314	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
82	2025-12-18 10:59:12.354046	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
81	2025-12-18 10:59:03.573925	t	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
80	2025-12-18 10:58:13.974602	t	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
79	2025-12-18 10:58:13.968812	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
78	2025-12-18 10:58:13.963031	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
77	2025-12-18 10:58:13.963031	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
75	2025-12-18 10:58:13.898574	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
76	2025-12-18 10:58:13.898574	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
74	2025-12-18 10:58:13.898574	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
73	2025-12-18 09:57:14.621318	t	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
72	2025-12-18 08:34:27.934771	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
71	2025-12-18 08:34:27.93047	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
70	2025-12-18 08:34:27.93047	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
67	2025-12-18 08:34:27.883035	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
68	2025-12-18 08:34:27.883035	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
69	2025-12-18 08:34:27.883035	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
66	2025-12-18 07:55:18.412763	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
64	2025-12-18 07:55:18.402998	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
65	2025-12-18 07:55:18.402998	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
62	2025-12-18 07:55:18.310458	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
63	2025-12-18 07:55:18.310458	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
61	2025-12-18 07:55:18.310458	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
60	2025-12-18 07:29:48.836726	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
59	2025-12-18 07:29:48.828274	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
58	2025-12-18 07:29:48.828274	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
55	2025-12-18 07:29:48.719872	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
57	2025-12-18 07:29:48.719872	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
56	2025-12-18 07:29:48.719872	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
54	2025-12-18 01:27:57.015649	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
53	2025-12-18 01:27:57.009295	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
52	2025-12-18 01:27:57.009295	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
49	2025-12-18 01:27:56.922329	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
51	2025-12-18 01:27:56.922329	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
50	2025-12-18 01:27:56.922329	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
47	2025-12-18 00:59:34.526685	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
43	2025-12-18 00:59:34.366937	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
44	2025-12-18 00:59:34.366937	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
45	2025-12-18 00:59:34.366937	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
42	2025-12-17 23:22:49.451569	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
41	2025-12-17 23:22:49.442735	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
40	2025-12-17 23:22:49.442735	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
38	2025-12-17 23:22:49.313202	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
37	2025-12-17 23:22:49.313202	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
39	2025-12-17 23:22:49.313202	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
36	2025-12-17 23:05:04.154129	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
35	2025-12-17 23:05:04.144691	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
34	2025-12-17 23:05:04.143934	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
31	2025-12-17 23:05:04.046276	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
33	2025-12-17 23:05:04.046276	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
32	2025-12-17 23:05:04.046276	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
30	2025-12-17 23:01:29.963397	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
28	2025-12-17 23:01:29.955711	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
29	2025-12-17 23:01:29.955711	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
27	2025-12-17 23:01:29.872913	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
26	2025-12-17 23:01:29.872913	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
25	2025-12-17 23:01:29.872913	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
24	2025-12-17 22:58:05.257835	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
22	2025-12-17 22:58:05.250816	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
23	2025-12-17 22:58:05.250816	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
20	2025-12-17 22:58:05.168456	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
21	2025-12-17 22:58:05.168456	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
19	2025-12-17 22:58:05.168456	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
18	2025-12-17 22:54:56.653594	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
17	2025-12-17 22:54:56.638899	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
16	2025-12-17 22:54:56.638899	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
15	2025-12-17 22:54:56.488263	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
14	2025-12-17 22:54:56.488263	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
13	2025-12-17 22:54:56.488263	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
12	2025-12-17 22:09:05.10791	t	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
10	2025-12-17 22:09:05.100393	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
11	2025-12-17 22:09:05.100393	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
8	2025-12-17 22:09:05.016265	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
9	2025-12-17 22:09:05.016265	t	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
7	2025-12-17 22:09:05.016265	t	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
5	2025-12-17 21:50:13.496346	t	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
3	2025-12-17 21:50:13.40848	t	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
347	2025-12-18 13:01:44.093319	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
348	2025-12-18 13:01:44.098097	f	Bạn đã thêm 1 x Ví Nam Da Bò Khắc Tên vào giỏ hàng. Giá: 450000.00	54	Thêm vào giỏ hàng	CART	3	\N
349	2025-12-18 13:01:44.102771	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
353	2025-12-18 13:04:29.047889	t	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	1	\N
352	2025-12-18 13:03:27.685419	t	Thanh toán thành công! Đơn hàng #8 đã được thanh toán 9190000.00 VND. Đơn hàng của bạn đang được xử lý.	8	Thanh toán thành công	PAYMENT	1	\N
350	2025-12-18 13:02:50.583036	t	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	1	\N
355	2025-12-18 13:04:56.278673	t	Thanh toán thành công! Đơn hàng #9 đã được thanh toán 3800000.00 VND. Đơn hàng của bạn đang được xử lý.	9	Thanh toán thành công	PAYMENT	1	\N
351	2025-12-18 13:02:54.320538	t	Đơn hàng #8 đã được tạo thành công! Tổng tiền: 9190000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	8	Đơn hàng mới	ORDER	1	\N
357	2025-12-18 13:08:57.496768	f	Đơn hàng #4 đã được tạo thành công! Tổng tiền: 54240000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	4	Đơn hàng mới	ORDER	3	\N
358	2025-12-18 13:08:57.498682	f	Thanh toán thành công! Đơn hàng #7 đã được thanh toán 3800000.00 VND. Đơn hàng của bạn đang được xử lý.	7	Thanh toán thành công	PAYMENT	3	\N
360	2025-12-18 13:08:57.499191	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
361	2025-12-18 13:08:57.499191	f	Đơn hàng #2 đã được tạo thành công! Tổng tiền: 127960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	2	Đơn hàng mới	ORDER	3	\N
362	2025-12-18 13:08:57.500202	f	Đơn hàng #1 đã được tạo thành công! Tổng tiền: 195970000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	1	Đơn hàng mới	ORDER	3	\N
365	2025-12-18 13:08:57.563657	f	Bạn đã thêm 4 x Laptop ASUS TUF Gaming F15 vào giỏ hàng. Giá: 15490000.00	2	Thêm vào giỏ hàng	CART	3	\N
366	2025-12-18 13:08:57.563657	f	Đơn hàng #3 đã được tạo thành công! Tổng tiền: 61960000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	3	Đơn hàng mới	ORDER	3	\N
367	2025-12-18 13:08:57.563657	f	Đơn hàng #4 đã được hủy thành công. Số tiền 54240000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	4	Đơn hàng đã hủy	ORDER	3	\N
368	2025-12-18 13:08:57.568682	f	Đơn hàng #5 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	5	Đơn hàng mới	ORDER	3	\N
370	2025-12-18 13:08:57.579756	f	Đơn hàng #6 đã được tạo thành công! Tổng tiền: 450000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	6	Đơn hàng mới	ORDER	3	\N
369	2025-12-18 13:08:57.581276	f	Bạn đã thêm 4 x Xiaomi Pad 6 8GB/128GB vào giỏ hàng. Giá: 7990000.00	24	Thêm vào giỏ hàng	CART	3	\N
371	2025-12-18 13:08:57.58452	f	Đơn hàng #5 đã được hủy thành công. Số tiền 3800000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	5	Đơn hàng đã hủy	ORDER	3	\N
372	2025-12-18 13:08:57.597148	f	Đơn hàng #6 đã được hủy thành công. Số tiền 450000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	6	Đơn hàng đã hủy	ORDER	3	\N
373	2025-12-18 13:08:57.597148	f	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
375	2025-12-18 13:08:57.603041	f	Đơn hàng #7 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	7	Đơn hàng mới	ORDER	3	\N
376	2025-12-18 13:08:57.615529	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
378	2025-12-18 13:08:57.635778	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
379	2025-12-18 13:08:57.652824	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
380	2025-12-18 13:08:57.682725	f	Bạn đã thêm 1 x Giày Converse Chuck 70 High Top vào giỏ hàng. Giá: 1900000.00	43	Thêm vào giỏ hàng	CART	3	\N
381	2025-12-18 13:08:57.709214	f	Bạn đã thêm 1 x Áo Hoodie Essentials Fear of God vào giỏ hàng. Giá: 1200000.00	44	Thêm vào giỏ hàng	CART	3	\N
382	2025-12-18 13:08:57.741166	f	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
383	2025-12-18 13:08:57.759594	f	Bạn đã thêm 3 x Nintendo Switch OLED Model vào giỏ hàng. Giá: 6990000.00	30	Thêm vào giỏ hàng	CART	3	\N
384	2025-12-18 13:08:57.787978	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
385	2025-12-18 13:08:57.810218	f	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	3	\N
386	2025-12-18 13:08:57.852394	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
387	2025-12-18 13:08:57.877761	f	Bạn đã thêm 1 x MacBook Air M1 2020 8GB/256GB vào giỏ hàng. Giá: 16500000.00	1	Thêm vào giỏ hàng	CART	3	\N
388	2025-12-18 13:08:57.89359	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
389	2025-12-18 13:08:57.914385	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
390	2025-12-18 13:08:57.932923	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
391	2025-12-18 13:08:57.950651	f	Bạn đã thêm 1 x Giày Nike Air Force 1 07 White vào giỏ hàng. Giá: 2690000.00	41	Thêm vào giỏ hàng	CART	3	\N
392	2025-12-18 13:08:57.966011	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
393	2025-12-18 13:08:57.980287	f	Bạn đã thêm 1 x Ví Nam Da Bò Khắc Tên vào giỏ hàng. Giá: 450000.00	54	Thêm vào giỏ hàng	CART	3	\N
394	2025-12-18 13:08:57.993991	f	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	3	\N
397	2025-12-18 13:11:04.364443	t	Thanh toán thành công! Đơn hàng #10 đã được thanh toán 11990000.00 VND. Đơn hàng của bạn đang được xử lý.	10	Thanh toán thành công	PAYMENT	1	\N
399	2025-12-18 13:18:53.798005	t	Bạn đã thêm 1 x RAM Laptop Kingston Fury vào giỏ hàng. Giá: 850000.00	19	Thêm vào giỏ hàng	CART	1	\N
401	2025-12-18 17:42:23.069793	t	Bạn đã thêm 1 x Giày Cao Gót Manolo Blahnik vào giỏ hàng. Giá: 25000000.00	47	Thêm vào giỏ hàng	CART	1	\N
400	2025-12-18 14:26:22.723309	t	Bạn đã thêm 1 x iPad Pro 12.9 inch M2 vào giỏ hàng. Giá: 31990000.00	23	Thêm vào giỏ hàng	CART	1	\N
398	2025-12-18 13:18:52.273579	t	Bạn đã thêm 1 x RAM Laptop Kingston Fury vào giỏ hàng. Giá: 850000.00	19	Thêm vào giỏ hàng	CART	1	\N
396	2025-12-18 13:10:31.944977	t	Đơn hàng #10 đã được tạo thành công! Tổng tiền: 11990000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	10	Đơn hàng mới	ORDER	1	\N
395	2025-12-18 13:10:28.744075	t	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	1	\N
377	2025-12-18 13:08:57.635778	t	Đơn hàng #8 đã được tạo thành công! Tổng tiền: 9190000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	8	Đơn hàng mới	ORDER	1	\N
374	2025-12-18 13:08:57.598343	t	Đơn hàng #9 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	9	Đơn hàng mới	ORDER	1	\N
364	2025-12-18 13:08:57.561366	t	Thanh toán thành công! Đơn hàng #8 đã được thanh toán 9190000.00 VND. Đơn hàng của bạn đang được xử lý.	8	Thanh toán thành công	PAYMENT	1	\N
363	2025-12-18 13:08:57.55583	t	Bạn đã thêm 1 x Giày Adidas Ultraboost Light vào giỏ hàng. Giá: 3800000.00	42	Thêm vào giỏ hàng	CART	1	\N
359	2025-12-18 13:08:57.497867	t	Bạn đã thêm 1 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	1	\N
356	2025-12-18 13:08:57.418952	t	Thanh toán thành công! Đơn hàng #9 đã được thanh toán 3800000.00 VND. Đơn hàng của bạn đang được xử lý.	9	Thanh toán thành công	PAYMENT	1	\N
354	2025-12-18 13:04:32.416939	t	Đơn hàng #9 đã được tạo thành công! Tổng tiền: 3800000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	9	Đơn hàng mới	ORDER	1	\N
404	2025-12-18 23:11:45.114755	t	Bạn đã thêm 3 x Apple Watch Series 9 vào giỏ hàng. Giá: 9190000.00	14	Thêm vào giỏ hàng	CART	1	\N
403	2025-12-18 21:54:16.478347	t	Bạn đã thêm 1 x Samsung Galaxy Tab S9 Ultra vào giỏ hàng. Giá: 26490000.00	22	Thêm vào giỏ hàng	CART	1	\N
405	2025-12-18 23:12:22.331462	f	Đơn hàng #11 đã được tạo thành công! Tổng tiền: 27570000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	11	Đơn hàng mới	ORDER	1	\N
406	2025-12-18 23:13:23.507836	f	Đơn hàng #11 đã được xác nhận thanh toán thành công!	11	Đơn hàng đã thanh toán	ORDER	1	\N
407	2025-12-18 23:13:24.480049	f	Thanh toán thành công! Đơn hàng #11 đã được thanh toán 27570000.00 VND. Đơn hàng của bạn đang được xử lý.	11	Thanh toán thành công	PAYMENT	1	\N
408	2025-12-18 23:13:24.549073	t	Thanh toán thành công! Đơn hàng #11 đã được thanh toán 27570000.00 VND. Đơn hàng của bạn đang được xử lý.	11	Thanh toán thành công	PAYMENT	1	\N
410	2025-12-18 23:42:55.629324	f	Đơn hàng #12 đã được hủy thành công. Số tiền 96820000.00 VND sẽ được hoàn lại (nếu đã thanh toán).	12	Đơn hàng đã hủy	ORDER	1	\N
409	2025-12-18 23:42:36.760946	t	Đơn hàng #12 đã được tạo thành công! Tổng tiền: 96820000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	12	Đơn hàng mới	ORDER	1	\N
412	2025-12-19 00:39:18.897094	f	Đơn hàng #9 đang được giao đến bạn. Vui lòng chú ý điện thoại!	9	Đơn hàng đang giao	ORDER	1	\N
413	2025-12-19 07:05:43.688427	f	Bạn đã thêm 1 x Case PC NZXT H9 Flow White vào giỏ hàng. Giá: 4190000.00	35	Thêm vào giỏ hàng	CART	1	\N
414	2025-12-19 07:05:43.74536	f	Bạn đã thêm 1 x Case PC NZXT H9 Flow White vào giỏ hàng. Giá: 4190000.00	35	Thêm vào giỏ hàng	CART	1	\N
416	2025-12-19 07:06:00.22944	f	Bạn đã thêm 1 x Case PC NZXT H9 Flow White vào giỏ hàng. Giá: 4190000.00	35	Thêm vào giỏ hàng	CART	1	\N
417	2025-12-19 07:06:01.743439	f	Bạn đã thêm 1 x Case PC NZXT H9 Flow White vào giỏ hàng. Giá: 4190000.00	35	Thêm vào giỏ hàng	CART	1	\N
411	2025-12-19 00:37:28.136378	t	Đơn hàng #1 đã hoàn thành. Cảm ơn bạn đã tin tưởng sử dụng dịch vụ!	1	Đơn hàng hoàn thành	ORDER	3	\N
418	2025-12-19 07:17:45.931582	t	Đơn hàng #9 đã được giao thành công. Cảm ơn bạn đã mua hàng!	9	Đơn hàng đã giao	ORDER	1	\N
402	2025-12-18 20:46:16.154396	t	Bạn đã thêm 1 x iPad Air 5 M1 64GB WiFi vào giỏ hàng. Giá: 11990000.00	21	Thêm vào giỏ hàng	CART	3	\N
419	2025-12-19 07:19:02.600247	t	Đơn hàng #7 đang được giao đến bạn. Vui lòng chú ý điện thoại!	7	Đơn hàng đang giao	ORDER	3	\N
420	2025-12-19 07:33:26.449899	t	Bạn đã thêm 1 x Balo North Face Fuse Box vào giỏ hàng. Giá: 990000.00	52	Thêm vào giỏ hàng	CART	3	\N
415	2025-12-19 07:05:45.936779	t	Bạn đã thêm 1 x Case PC NZXT H9 Flow White vào giỏ hàng. Giá: 4190000.00	35	Thêm vào giỏ hàng	CART	1	\N
421	2025-12-19 10:45:22.738397	f	Bạn đã thêm 1 x Laptop Dell Latitude 5511 vào giỏ hàng. Giá: 5555555.00	3	Thêm vào giỏ hàng	CART	1	\N
422	2025-12-19 10:47:05.989373	f	Đơn hàng #13 đã được tạo thành công! Tổng tiền: 76490000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	13	Đơn hàng mới	ORDER	1	\N
423	2025-12-19 10:47:21.558928	t	Đơn hàng #14 đã được tạo thành công! Tổng tiền: 5555555.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	14	Đơn hàng mới	ORDER	1	\N
424	2025-12-20 09:07:46.436771	f	Bạn đã thêm 1 x iPad Pro 12.9 inch M2 vào giỏ hàng. Giá: 31990000.00	23	Thêm vào giỏ hàng	CART	1	\N
425	2025-12-20 09:07:52.153646	f	Đơn hàng #15 đã được tạo thành công! Tổng tiền: 31990000.00 VND. Vui lòng thanh toán để hoàn tất đơn hàng.	15	Đơn hàng mới	ORDER	1	\N
426	2025-12-20 09:12:20.421455	f	Đơn hàng #9 đã hoàn thành. Cảm ơn bạn đã tin tưởng sử dụng dịch vụ!	9	Đơn hàng hoàn thành	ORDER	1	\N
427	2025-12-20 09:31:14.617658	f	Đơn hàng #15 đã được hủy. Số tiền 31.990.000 ₫ sẽ được hoàn lại (nếu đã thanh toán).	15	Đơn hàng đã hủy	ORDER	1	USER
428	2025-12-20 09:31:29.20887	f	Bạn đã thêm 1 x Flycam DJI Mini 4 Pro vào giỏ hàng. Giá: 19990000.00	28	Thêm vào giỏ hàng	CART	1	USER
429	2025-12-20 09:31:47.507994	f	Đơn hàng #16 đã được tạo thành công! Tổng tiền: 19.990.000 ₫. Vui lòng thanh toán để hoàn tất đơn hàng.	16	Đơn hàng mới	ORDER	1	USER
431	2025-12-20 09:32:26.654776	f	Đơn hàng #10 đang được giao đến bạn. Vui lòng chú ý điện thoại!	10	Đơn hàng đang giao	ORDER	1	USER
432	2025-12-20 09:32:29.467842	f	Đơn hàng #2 đã được giao thành công. Cảm ơn bạn đã mua hàng!	2	Đơn hàng đã giao	ORDER	3	USER
433	2025-12-20 09:33:35.070463	f	Đơn hàng #16 đã được xác nhận thanh toán thành công!	16	Đơn hàng đã thanh toán	ORDER	1	USER
435	2025-12-20 09:33:35.752686	f	Thanh toán thành công! Đơn hàng #16 đã được thanh toán 19990000.00 VND. Đơn hàng của bạn đang được xử lý.	16	Thanh toán thành công	PAYMENT	1	USER
436	2025-12-20 09:33:35.795786	f	Thanh toán thành công! Đơn hàng #16 đã được thanh toán 19990000.00 VND. Đơn hàng của bạn đang được xử lý.	16	Thanh toán thành công	PAYMENT	1	USER
434	2025-12-20 09:33:35.082083	t	💰 Đơn hàng #16 đã thanh toán 19.990.000 ₫. Vui lòng chuẩn bị hàng và giao cho vận chuyển.	16	💰 Thanh toán thành công	ORDER	\N	ADMIN
430	2025-12-20 09:31:47.513841	t	🛒 Đơn hàng mới #16 từ User #1. Tổng tiền: 19.990.000 ₫. Trạng thái: Chờ thanh toán.	16	📦 Đơn hàng mới	ORDER	\N	ADMIN
\.


--
-- TOC entry 3425 (class 0 OID 0)
-- Dependencies: 217
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 436, true);


--
-- TOC entry 3272 (class 2606 OID 16395)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


-- Completed on 2025-12-20 10:21:09

--
-- PostgreSQL database dump complete
--

\unrestrict cqqNt0WmHQ4lFapG2EdIe3sLmaUBxgcDqu3eJZb5YOnCWKOV7JUwLGkzfPrwszS

