--
-- PostgreSQL database dump
--

\restrict gRNuHTp1luubiggc0KZhjBhCCu72pxjflfFielUcuE7WFrKe0bgZIzLOFp07mCf

-- Dumped from database version 17.7
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-20 10:19:55

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16386)
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    discount_price numeric(19,2),
    price numeric(19,2) NOT NULL,
    product_id bigint NOT NULL,
    product_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    subtotal numeric(19,2) NOT NULL,
    order_id bigint NOT NULL,
    product_description text,
    product_image character varying(1024)
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16385)
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16392)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    order_code character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    total_amount numeric(19,2) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16391)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3429 (class 0 OID 16386)
-- Dependencies: 218
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (id, discount_price, price, product_id, product_name, quantity, subtotal, order_id, product_description, product_image) FROM stdin;
1	29900000.00	32000000.00	4	Laptop Lenovo ThinkPad X1	5	149500000.00	1	\N	\N
2	15490000.00	16990000.00	2	Laptop ASUS TUF Gaming F15	3	46470000.00	1	\N	\N
3	15490000.00	16990000.00	2	Laptop ASUS TUF Gaming F15	4	61960000.00	2	\N	\N
4	16500000.00	18990000.00	1	MacBook Air M1 2020 8GB/256GB	4	66000000.00	2	\N	\N
5	15490000.00	16990000.00	2	Laptop ASUS TUF Gaming F15	4	61960000.00	3	\N	\N
6	16500000.00	18990000.00	1	MacBook Air M1 2020 8GB/256GB	1	16500000.00	4	Chip Apple M1 mạnh mẽ, pin trâu 18 tiếng, thiết kế nhôm nguyên khối.	https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=400&q=80
7	2690000.00	2990000.00	41	Giày Nike Air Force 1 07 White	2	5380000.00	4	Huyền thoại sneaker trắng, để phối đồ, phong cách đường phố.	https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=400&q=80
8	6990000.00	7990000.00	30	Nintendo Switch OLED Model	2	13980000.00	4	Màn hình OLED 7 inch rực rỡ, chơi game cầm tay tiện lợi.	https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=400&q=80
9	9190000.00	9890000.00	14	Apple Watch Series 9	2	18380000.00	4	Màn hình luôn bật sáng hơn, thao tác Chạm hai lần mới.	https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=400&q=80
10	3800000.00	4200000.00	42	Giày Adidas Ultraboost Light	1	3800000.00	5	Công nghệ đệm Boost êm ái, hỗ trợ chạy bộ chuyên nghiệp.	https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=400&q=80
11	450000.00	550000.00	54	Ví Nam Da Bò Khắc Tên	1	450000.00	6	Da bò sáp ngựa điên, handmade 100%, bảo hành 5 năm.	https://images.unsplash.com/photo-1627123424574-18bd7584863c?auto=format&fit=crop&w=400&q=80
12	3800000.00	4200000.00	42	Giày Adidas Ultraboost Light	1	3800000.00	7	Công nghệ đệm Boost êm ái, hỗ trợ chạy bộ chuyên nghiệp.	https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=400&q=80
13	9190000.00	9890000.00	14	Apple Watch Series 9	1	9190000.00	8	Màn hình luôn bật sáng hơn, thao tác Chạm hai lần mới.	https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=400&q=80
14	3800000.00	4200000.00	42	Giày Adidas Ultraboost Light	1	3800000.00	9	Công nghệ đệm Boost êm ái, hỗ trợ chạy bộ chuyên nghiệp.	https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=400&q=80
15	11990000.00	13990000.00	21	iPad Air 5 M1 64GB WiFi	1	11990000.00	10	Sức mạnh chip M1, màn hình Liquid Retina 10.9 inch sắc nét.	https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=400&q=80
16	9190000.00	9890000.00	14	Apple Watch Series 9	3	27570000.00	11	Màn hình luôn bật sáng hơn, thao tác Chạm hai lần mới.	https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=400&q=80
17	\N	31990000.00	23	iPad Pro 12.9 inch M2	3	95970000.00	12	Hiệu năng đỉnh cao chip M2, màn hình Mini-LED XDR chân thực.	https://images.unsplash.com/photo-1587033411391-5d9e51cce126?auto=format&fit=crop&w=400&q=80
18	850000.00	990000.00	19	RAM Laptop Kingston Fury	1	850000.00	12	DDR4 3200MHz, tự động ép xung, tối ưu cho gaming.	https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=400&q=80
19	26490000.00	29990000.00	22	Samsung Galaxy Tab S9 Ultra	1	26490000.00	13	Máy tính bảng màn hình khổng lồ 14.6 inch, kèm bút S-Pen, chống nước.	https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?auto=format&fit=crop&w=400&q=80
20	\N	25000000.00	47	Giày Cao Gót Manolo Blahnik	2	50000000.00	13	Thiết kế mũi nhọn sang trọng, đính đá pha lê, dành cho dạ tiệc.	https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=400&q=80
21	5555555.00	14500000.00	3	Laptop Dell Latitude 5511	1	5555555.00	14	Dòng máy doanh nhân bền bỉ, hiệu năng ổn định, bảo mật vân tay.	https://nhom5sbucket.s3.ap-southeast-1.amazonaws.com/products/thumbnails/6c58d905-0e1d-4908-b854-54a7a2955343-asus.jpg
22	\N	31990000.00	23	iPad Pro 12.9 inch M2	1	31990000.00	15	Hiệu năng đỉnh cao chip M2, màn hình Mini-LED XDR chân thực.	https://images.unsplash.com/photo-1587033411391-5d9e51cce126?auto=format&fit=crop&w=400&q=80
23	19990000.00	21500000.00	28	Flycam DJI Mini 4 Pro	1	19990000.00	16	Quay phim 4K/60fps HDR, cảm biến tránh va chạm đa hướng.	https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=400&q=80
\.


--
-- TOC entry 3431 (class 0 OID 16392)
-- Dependencies: 220
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, created_at, updated_at, order_code, status, total_amount, user_id) FROM stdin;
4	2025-12-18 05:09:03.263629+00	2025-12-18 05:10:55.323544+00	ORD-20251218-0001	CANCELLED	54240000.00	3
5	2025-12-18 05:14:16.530327+00	2025-12-18 05:35:21.568916+00	ORD-20251218-0002	CANCELLED	3800000.00	3
6	2025-12-18 05:30:39.928177+00	2025-12-18 05:35:34.414666+00	ORD-20251218-0003	CANCELLED	450000.00	3
8	2025-12-18 06:02:54.08542+00	2025-12-18 06:37:00.175264+00	ORD-20251218-0005	SHIPPING	9190000.00	1
3	2025-12-17 03:30:42.362902+00	2025-12-18 06:48:34.887929+00	ORD-20251217-0002	COMPLETED	61960000.00	3
11	2025-12-18 16:12:21.876404+00	2025-12-18 16:13:23.506847+00	ORD-20251218-0008	PAID	27570000.00	1
12	2025-12-18 16:42:36.673312+00	2025-12-18 16:42:55.617889+00	ORD-20251218-0009	CANCELLED	96820000.00	1
1	2025-12-16 04:24:28.025476+00	2025-12-18 17:37:28.081522+00	ORD-20251216-0001	COMPLETED	195970000.00	3
7	2025-12-18 05:35:42.841344+00	2025-12-19 00:19:02.5765+00	ORD-20251218-0004	SHIPPING	3800000.00	3
13	2025-12-19 03:47:05.714389+00	2025-12-19 03:47:05.714389+00	ORD-20251219-0001	PENDING_PAYMENT	76490000.00	1
14	2025-12-19 03:47:21.4923+00	2025-12-19 03:47:21.4923+00	ORD-20251219-0002	PENDING_PAYMENT	5555555.00	1
9	2025-12-18 06:04:32.374786+00	2025-12-20 02:12:20.399958+00	ORD-20251218-0006	COMPLETED	3800000.00	1
15	2025-12-20 02:07:51.912677+00	2025-12-20 02:31:14.51903+00	ORD-20251220-0001	CANCELLED	31990000.00	1
10	2025-12-18 06:10:31.763728+00	2025-12-20 02:32:26.651013+00	ORD-20251218-0007	SHIPPING	11990000.00	1
2	2025-12-17 03:26:02.208168+00	2025-12-20 02:32:29.472227+00	ORD-20251217-0001	DELIVERED	127960000.00	3
16	2025-12-20 02:31:47.445024+00	2025-12-20 02:33:35.066844+00	ORD-20251220-0002	PAID	19990000.00	1
\.


--
-- TOC entry 3437 (class 0 OID 0)
-- Dependencies: 217
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_id_seq', 23, true);


--
-- TOC entry 3438 (class 0 OID 0)
-- Dependencies: 219
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 16, true);


--
-- TOC entry 3277 (class 2606 OID 16390)
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3279 (class 2606 OID 16396)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 3281 (class 2606 OID 16398)
-- Name: orders ukdhk2umg8ijjkg4njg6891trit; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukdhk2umg8ijjkg4njg6891trit UNIQUE (order_code);


--
-- TOC entry 3282 (class 2606 OID 16399)
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


-- Completed on 2025-12-20 10:19:55

--
-- PostgreSQL database dump complete
--

\unrestrict gRNuHTp1luubiggc0KZhjBhCCu72pxjflfFielUcuE7WFrKe0bgZIzLOFp07mCf

