--
-- PostgreSQL database dump
--

\restrict OSEKed4idwaqOG4JnGvMywQwzGo5xs0F2lIxTe02u1fVDuiQYLyExG65XYuy7tE

-- Dumped from database version 17.7
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-20 10:22:14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16386)
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    amount numeric(19,2) NOT NULL,
    bank_code character varying(50),
    card_type character varying(50),
    order_id bigint NOT NULL,
    payment_method character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    transaction_id character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16385)
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3424 (class 0 OID 16386)
-- Dependencies: 218
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payments (id, created_at, updated_at, amount, bank_code, card_type, order_id, payment_method, status, transaction_id, user_id) FROM stdin;
1	2025-12-18 05:16:14.913952+00	2025-12-18 05:35:02.191872+00	3800000.00	\N	\N	5	VNPAY	PENDING	\N	3
6	2025-12-18 05:30:43.745898+00	2025-12-18 05:35:27.198479+00	450000.00	\N	\N	6	VNPAY	PENDING	\N	3
7	2025-12-18 05:35:44.68042+00	2025-12-18 05:48:33.097801+00	3800000.00	NCB	ATM	7	VNPAY	COMPLETED	15352059	3
8	2025-12-18 06:02:56.140269+00	2025-12-18 06:03:27.637118+00	9190000.00	NCB	ATM	8	VNPAY	COMPLETED	15352071	1
9	2025-12-18 06:04:33.857877+00	2025-12-18 06:04:56.249503+00	3800000.00	NCB	ATM	9	VNPAY	COMPLETED	15352074	1
10	2025-12-18 06:10:34.632912+00	2025-12-18 06:11:04.324613+00	11990000.00	NCB	ATM	10	VNPAY	COMPLETED	15352092	1
11	2025-12-18 16:12:26.460599+00	2025-12-18 16:13:24.52649+00	27570000.00	NCB	ATM	11	VNPAY	COMPLETED	15353374	1
12	2025-12-20 02:05:51.890975+00	2025-12-20 02:05:51.890975+00	5555555.00	\N	\N	14	VNPAY	PENDING	\N	1
13	2025-12-20 02:32:38.641324+00	2025-12-20 02:33:35.769094+00	19990000.00	NCB	ATM	16	VNPAY	COMPLETED	15356028	1
\.


--
-- TOC entry 3430 (class 0 OID 0)
-- Dependencies: 217
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_id_seq', 13, true);


--
-- TOC entry 3275 (class 2606 OID 16390)
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- TOC entry 3277 (class 2606 OID 16395)
-- Name: payments uk8vo36cen604as7etdfwmyjsxt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk8vo36cen604as7etdfwmyjsxt UNIQUE (order_id);


--
-- TOC entry 3271 (class 1259 OID 16391)
-- Name: idx_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_id ON public.payments USING btree (order_id);


--
-- TOC entry 3272 (class 1259 OID 16393)
-- Name: idx_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_status ON public.payments USING btree (status);


--
-- TOC entry 3273 (class 1259 OID 16392)
-- Name: idx_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_id ON public.payments USING btree (user_id);


-- Completed on 2025-12-20 10:22:14

--
-- PostgreSQL database dump complete
--

\unrestrict OSEKed4idwaqOG4JnGvMywQwzGo5xs0F2lIxTe02u1fVDuiQYLyExG65XYuy7tE

